server:
  servlet:
    context-path: /cabinet
  port: 8082

spring:
  application:
    name: My_House_24
  datasource:
    url: 'jdbc:mysql://localhost:3306/my_house_24'
    username: 'user'
    password: 'user'
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    username: test.in.odessa@gmail.com
    password: sggcjhmrombnkscg
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    protocol: smtp
  security:
    user:
      name: user
      password: user
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.3bea1ea44c34a11b
            client-secret: b48b48ba6f45c1e63858a6f4c3534b93fe1e760f
          google:
            client-id: 799352228923-un3c3udmi4lj4e9hrjn6hqe15rd3rgu5.apps.googleusercontent.com
            client-secret: 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
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: email


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

upload:
  path: "C:/Users/Amir Banov/files"

app:
  jwt:
    secret: SV9ET04nVF9LTk9XX1RIRV9TRUNSRVRfVE9LRU4=
